# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.rightleg] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_rightleg
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.leftleg] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_leftleg
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.bottom] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_bottom
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.cape] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_cape
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.hat] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_hat
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.head_hat] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_head_hat
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.rightarm] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_rightarm
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.leftarm] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_leftarm
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.staff] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_staff
execute on passengers if entity @s[tag=aj.glacial_wraith.bone.jacket] run function animated_java:glacial_wraith/variants/default/zzz/apply_to_bone_jacket
return 1