# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.cape] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_cape set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.hat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.head_hat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head_hat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rightarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.staff] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_staff set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.glacial_wraith.node.jacket] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jacket set from storage aj:uuid main.out