# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.minion_summon.frame matches 56.. run scoreboard players set @s aj.minion_summon.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.minion_summon.frame
execute at @s run function animated_java:glacial_wraith/animations/minion_summon/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.minion_summon.frame 1