# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.wand_attack.frame dummy
scoreboard objectives add aj.minion_summon.frame dummy
scoreboard objectives add aj.rage_mode_enter.frame dummy
scoreboard objectives add aj.rage_mode_exit.frame dummy