# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.glacial_wraith.root] run return 0
execute if entity @s[tag=aj.glacial_wraith.animation.wand_attack.playing] run function animated_java:glacial_wraith/animations/wand_attack/zzz/on_tick
execute if entity @s[tag=aj.glacial_wraith.animation.minion_summon.playing] run function animated_java:glacial_wraith/animations/minion_summon/zzz/on_tick
execute if entity @s[tag=aj.glacial_wraith.animation.rage_mode_enter.playing] run function animated_java:glacial_wraith/animations/rage_mode_enter/zzz/on_tick
execute if entity @s[tag=aj.glacial_wraith.animation.rage_mode_exit.playing] run function animated_java:glacial_wraith/animations/rage_mode_exit/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~