# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.glacial_wraith.animation.wand_attack.playing
tag @s remove aj.glacial_wraith.animation.minion_summon.playing
tag @s remove aj.glacial_wraith.animation.rage_mode_enter.playing
tag @s remove aj.glacial_wraith.animation.rage_mode_exit.playing
tag @s remove aj.glacial_wraith.animation.death.playing