# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_rightleg) {transformation: [-1f,0f,0f,-0.1826f,0f,1f,0f,0.0746f,0f,0f,-1f,0.2452f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.522f,0f,0f,-1f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.522f,0f,0f,-1f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1f,0f,0f,-0.0313f,0f,1f,0f,0.4126f,0f,0f,-1f,0.0378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hat) {transformation: [-0.9659f,-0.2588f,0f,-0.0545f,-0.2588f,0.9659f,0f,0.8313f,0f,0f,-1f,-0.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_hat) {transformation: [-0.9848f,-0.1736f,0f,0f,-0.1736f,0.9848f,0f,0.522f,0f,0f,-1f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightarm) {transformation: [-1f,0f,0f,-0.1736f,0f,0.9537f,-0.3007f,0.5015f,0f,-0.3007f,-0.9537f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftarm) {transformation: [-1f,0f,0f,0.1736f,0f,0.866f,-0.5f,0.5015f,0f,-0.5f,-0.866f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0.6235f,0f,-1.0799f,0.4375f,-0.5399f,1.0799f,-0.3117f,0.4375f,0.9352f,0.6235f,0.5399f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_jacket) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.522f,0f,0f,-1f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] run function animated_java:glacial_wraith/variants/rage_mode/apply