# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.glacial_wraith.animation.rage_mode_exit.playing
scoreboard players set @s aj.rage_mode_exit.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:glacial_wraith/animations/rage_mode_exit/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only